Contribution FollowersCounter
LeoTechmaker/FollowersCounter pull request #4
Opened 2018-04-12 09:55 UTC by l3ch4tno1r

Bonjour,

Je me permets de vous soumettre ma contribution au projet FollowerCounter. Il s'agit principalement d'épuration de code afin de le rendre plus simple à comprendre et à maintenir :)

Vous trouverez des infos sur les modifs dans les commentaires des commit de ma fork. Si vous avez des remarques ou des questions, n'hésitez pas à me le faire savoir ;)

@ +

Le Chat Noir

2018-04-12 11:57 UTC, Fardenco commented
Salut,
Le compteur est chez Léo, j'ai commandé de quoi en faire un juste pour les tests mais je n'ai pas encore reçu les panneaux de LEDs.
Je ne peux donc pas tester tes modifications.
Mais déjà sans tester, il y a un problème que je vois, c'est que tu as mis à jour le fichier "settings.txt" pour y intégrer ta clé d'API YouTube. Cette clé devrait rester privée, toutes les actions faites grâce à elle sont reliées à ton compte..
Donc je te conseille de la désactiver dès maintenant et d'en récupérer une nouvelle que tu garderas privée ;)

Ensuite, il faudrait supprimer les fichiers qui ne sont pas nécessaires au projet (pas mal de fichiers générés par VS)

Si non, il y a une nouvelle version du code qui ne nécessite plus de passer par un ordinateur, tout est embarqué sur un microcontrôleur qui dispose d'une connectivité WiFi. Je n'ai pas encore mis en ligne ce programme, car il me reste des ajustements à faire dessus (mais encore une fois, le compteur est chez Léo donc c'est galère de travailler dessus), mais tu peux déjà voir le résultat dans cette vidéo : 
https://www.youtube.com/watch?v=sWKcnsrpM98

Je reviens vers toi quand j'aurais reçu ce qu'il me faut pour tout tester

2018-04-12 12:35 UTC, Fardenco commented
Oui, je pense que c'est ce que je vais faire.
Je pense que la version qui nécessite un PC pour fonctionner n'aura plus vraiment d'intérêt, mais je vais quand même la laisser en ligne, au cas où quelqu'un en ait un jour l'utilité

2018-05-28 14:27 UTC, Arecdark commented
Salut, et merci pour votre travaille.
Je viens de recevoir le ESP-I2E WeMos D1 WiFi et les dalles de LED pour faire le deuxième tuto sans avoir la nécessité du PC, Auriez-vous une idée de la disponibilité du nouveau code ?
J'ai hâte de tester ce compteur ;)

2018-05-28 16:35 UTC, Fardenco requested changes
Fichiers inutiles à supprimer

2018-05-28 17:03 UTC, Fardenco commented
La mise à jour est en ligne.
Beaucoup de choses ont changées, comme je te l'avais dit, le code que tu as modifié n'existe plus sur cette version.
Si tu veux toujours publier ton code, tu peux le faire sur la branche "Version-PC"

2018-05-28 17:06 UTC, closed without merging

2018-05-28 17:07 UTC, Arecdark commented
Merci beaucoup !